### PR TITLE
NatGen-base.commons-jxpath.mid-996.idx-12519.2.buggy

### PR DESCRIPTION
**Pull request by Seif2001**
Added proper indentation

### CODE REVIEW

**Comment by yhjboong** [comment]
Line 125 should be an 8-space indentation since you are continuing the line! (See line 144-145) :)

**Comment by Seif2001** [comment]
Done
Thanks

**Comment by darko-marinov** [comment]
Please check `This branch cannot be rebased due to conflicts`. Sorry if we accepted some PR before yours.

**Comment by darko-marinov** [comment]
Closing due to conflicts. Sorry if we accepted some PR before yours.

**Comment by darko-marinov** [comment]
Reopening to delete the `LICENSE` file.

**Pull request merged**
