### PR TITLE
NatGen-base.commons-collections.mid-2468.idx-5126.2.buggy

### PR DESCRIPTION
**Pull request by Mashequr**
Reformatted the file (fixed indentation)

### CODE REVIEW

**Comment by yhjboong** [comment]
I suggest to push the line `cursors.add(null);` Other part looks great :)

**Comment by Mashequr** [comment]
> I suggest to push the line `cursors.add(null);` Other part looks great :)

Done! Thanks!

**Comment by sugamadhiakri** [comment]
discard

**Comment by darko-marinov** [comment]
@sugamadhiakri Why would we discard this? The reformatting itself looks good to me. The question is whether the mutant was formed incorrectly in the first place and did not even compile.

**Comment by sugamadhiakri** [comment]
I thought we weren't formatting the buggy branches.

**Comment by darko-marinov** [comment]
We don't need buggy branches for the work on mutants, but we might find this reformatting useful. I'll accept it (although it changes even the compilability of the code).

**Pull request merged**
