### PR TITLE
leam-base.jsoup.mid-1014.idx-188749.3.mutant

### PR DESCRIPTION
**Pull request by Arsh-Khan**
Updated Indentation in Mutated Code

### CODE REVIEW

**Comment by faustinoaq** [comment]
Needs to fix indentation to match formatting

**Comment by darko-marinov** [comment]
@Arsh-Khan please address this in the next 2-3 days, or we'll assign to someone else.

**Comment by Arsh-Khan** [comment]
I have fixed the indentation! Please let me know if there are any sections you still feel are not indented properly.

**Comment by faustinoaq** [comment]
> I have fixed the indentation! Please let me know if there are any sections you still feel are not indented properly.

If you see the indentation of the file Parser.java your code block is indented more see: lines 109-111 (yours) vs 100-102 (Parser.java)

https://github.com/Intelligent-CAT-Lab/UIUCPlus/blob/fc391671992a962fe2dee7b3755f97f64e85852a/jsoup/src/main/java/org/jsoup/parser/Parser.java#L95-L112

**Comment by Arsh-Khan** [comment]
Sorry for the oversight, I have corrected the indentation.

**Pull request merged**
