### PR TITLE
leam-base.commons-collections.mid-347.idx-6107.25.mutant

### PR DESCRIPTION
**Pull request by yhjboong**

### CODE REVIEW

**Comment by PentesterPriyanshu** [comment]
correct

**Comment by darko-marinov** [comment]
Not having spaces in the changed line with `if` looks unusual. Did you compare this with the original code?

**Comment by darko-marinov** [comment]
@PentesterPriyanshu did you look into https://github.com/yhjboong/UIUCPlus/compare/461dfea3626452643d4138fef934535979fe87e9..leam-base.commons-collections.mid-347.idx-6107.25.mutant

**Comment by darko-marinov** [comment]
@yhjboong please correct those space per https://github.com/yhjboong/UIUCPlus/compare/461dfea3626452643d4138fef934535979fe87e9..leam-base.commons-collections.mid-347.idx-6107.25.mutant

**Comment by yhjboong** [comment]
> @yhjboong please correct those space per https://github.com/yhjboong/UIUCPlus/compare/461dfea3626452643d4138fef934535979fe87e9..leam-base.commons-collections.mid-347.idx-6107.25.mutant

Hi, Darko. Thanks for the notification on Discord. Just to clarify: does "those space per" mean space per tab (like 2, 4, 8)? Thanks in advance.

**Comment by darko-marinov** [comment]
Did you compare your changes to the original code?

**Comment by yhjboong** [comment]
> Did you compare your changes to the original code?

Yes, I thought we were talking about the below change:
image
Now it is merged though.

**Pull request merged**
