### PR TITLE
Update of  parser.java

### PR DESCRIPTION
**Pull request by ahkatlio**

### CODE REVIEW

**Comment by ahkatlio** [comment]
Added null checks to ensure @Nonnull compliance in Parser methods

**Comment by darko-marinov** [comment]
Are you trying to do the eval task? Please focus on labeling the mutants and optionally reformatting the changes to match the style of the surrounding code. We don't need any new `null` checks.

**Comment by alibrahimzada** [comment]
Please see the instruction document on how to name your pull request.

**Comment by alibrahimzada** [comment]
Please see the instruction document on how to name your pull request.

**Comment by darko-marinov** [comment]
@ahkatlio do you want to revise this PR in the next 2-3 days to address the requirement, or should we just close the PR?

**Comment by ahkatlio** [comment]
> @ahkatlio do you want to revise this PR in the next 2-3 days to address the requirement, or should we just close the PR?

I would like to revise this PR.

**Comment by darko-marinov** [comment]
@ahkatlio I didn't see any updates from you, so closing this PR.

**Pull request closed without merging**
