### PR TITLE
leam-base.gson.mid-121.idx-102444.2.mutant

### PR DESCRIPTION
**Pull request by pranit-sinha**

### CODE REVIEW

**Comment by faustinoaq** [comment]
Needs to fix indentation to match formatting

**Comment by darko-marinov** [comment]
@pranit-sinha please fix this case as well as all others where someone asked for a change.

**Comment by pranit-sinha** [comment]
@faustinoaq Could you confirm whether it's been sufficiently fixed?

**Comment by faustinoaq** [comment]
> @faustinoaq Could you confirm whether it's been sufficiently fixed?

Hi @pranit-sinha still needs to fix indentation lines 178, 180-182 please see the formatting for this file:

https://github.com/Intelligent-CAT-Lab/UIUCPlus/blob/c9baaa2252b767b1566f83da305db6c512f0a4c1/gson/gson/src/main/java/com/google/gson/internal/bind/JsonTreeWriter.java#L168-L190

**Comment by pranit-sinha** [comment]
@faustinoaq Ah, okay - done now

**Comment by darko-marinov** [comment]
@faustinoaq LGTY?

**Comment by faustinoaq** [comment]
> @faustinoaq LGTY?

LGTM!

**Pull request merged**
